name: gh-pages deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # build the project using node
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install node_modules dependency
      - name: Install dependencies
        run: npm install
        env:
          CI: false

      # Deploy to gh-pages (included npm run build and gh-pages -d build inside)
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          CI: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ github.token }}
          repository: ${{ github.repository }}
